CREATE TABLE [dbo].[ContentStoreObjects]
(
[UID] [int] NOT NULL IDENTITY(1, 1),
[timestamp1] [datetime] NOT NULL,
[class_type] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ObjectNAME] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ParentName] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SourceReportIfReportView] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ParentClass_Type] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[parent_cmid] [int] NOT NULL,
[object_cmid] [int] NOT NULL,
[ObjectPath] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NC_Schedule_PK_ID] [int] NULL,
[MessageID] [int] NULL,
[obj_modified] [datetime] NULL,
[obj_disabled] [tinyint] NULL,
[obj_classid] [tinyint] NOT NULL,
[DISPSEQ] [int] NOT NULL,
[obj_owner] [int] NULL,
[Store_id] [char] (33) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[news_type] [smallint] NULL,
[STARTDATE] [datetime] NULL,
[ENDDATE] [datetime] NULL,
[ENDTYPE] [tinyint] NULL,
[EVERYNPERIODS] [int] NULL,
[DAILYPERIOD] [tinyint] NULL,
[MONTHLYABSDAY] [tinyint] NULL,
[MONTHLYRELDAY] [tinyint] NULL,
[MONTHLYRELWEEK] [tinyint] NULL,
[CMOBJPROP2_type] [tinyint] NULL,
[YEARLYABSDAY] [tinyint] NULL,
[YEARLYABSMONTH] [tinyint] NULL,
[YEARLYRELDAY] [tinyint] NULL,
[YEARLYRELMONTH] [tinyint] NULL,
[YEARLYRELWEEK] [tinyint] NULL,
[CMOBJPROPS2_active] [bit] NULL,
[WEEKLYMONDAY] [bit] NULL,
[WEEKLYTUESDAY] [bit] NULL,
[WEEKLYWEDNESDAY] [bit] NULL,
[WEEKLYTHURSDAY] [bit] NULL,
[WEEKLYFRIDAY] [bit] NULL,
[WEEKLYSATURDAY] [bit] NULL,
[WEEKLYSUNDAY] [bit] NULL,
[TaskSchedule_Description] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LAST_EXECUTION_AT] [numeric] (19, 0) NULL,
[NEXT_EXECUTION_REQUEST] [numeric] (19, 0) NULL,
[IS_ACTIVE] [int] NULL,
[IS_ESCALATION] [int] NULL,
[Schedule_type] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LASTMOD_BY] [char] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LASTMOD_TIME] [datetime] NULL,
[MODCOUNT] [int] NULL,
[TIMEZONE] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[START_DATE] [numeric] (19, 0) NULL,
[END_DATE] [numeric] (19, 0) NULL,
[REPEAT_FOREVER] [int] NULL,
[nc_schedule_active] [int] NULL,
[VALID_SCHEDULE] [int] NULL,
[USE_DAY_NUMBER] [int] NULL,
[DAY_OF_MONTH] [int] NULL,
[DAY_OF_WEEK] [int] NULL,
[DAY_OF_WEEK_IN_MONTH] [int] NULL,
[MONTH_OF_YEAR] [int] NULL,
[REPEAT_INTERVAL] [int] NULL,
[DAYS_OF_WEEK] [int] NULL,
[FIXED_INTERVAL_TYPE] [int] NULL,
[Trigger_name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Bui] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ContentStoreObjects] ADD CONSTRAINT [PK_ContentStoreObjects] PRIMARY KEY CLUSTERED  ([UID]) ON [PRIMARY]
GO
